### ISSUE TITLE
Ver. 4.1.1. does not load

### ISSUE THREAD

**Issue by plajos1** [dcajasn/Riskfolio-Lib#155] opened 2023-04-13 12:03 UTC
I have tested this program regularly with the actual stock market data. 

I was surprised by the newest version(4.1.1):

ModuleNotFoundError: No module named 'riskfolio.external.functions'

error message comes up.  I do not find what could cause this problem. (Running it with Python 3.8 under PyCharm)

**Comment by dcajasn** [comment] 2023-04-13 12:36
Hi @plajos1, use anaconda or winpython. Riskfolio-Lib was designed to work with scientific python distributions.

**Comment by plajos1** [comment] 2023-04-13 16:06
Well it worked at least for one year with the standard Python 3.8. Just wanted you to know that something has changed with the new version.

**Comment by dcajasn** [comment] 2023-04-13 16:47
The problem is not Python 3.8, I think that the problem is that you are not using a scientific Python distribution. I recommend you to install anaconda or winpython and then use that distribution with Pycharm.

**Comment by plajos1** [comment] 2023-04-13 19:18
In the Conda i encountered this:
# Plotting the composition of the portfolio

ax = rp.plot_pie(w=w, title='Sharpe FM Mean Variance', others=0.05, nrow=25, cmap = "tab20",
                 height=6, width=10, ax=None)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[14], line 3
      1 # Plotting the composition of the portfolio
----> 3 ax = rp.plot_pie(w=w, title='Sharpe FM Mean Variance', others=0.05, nrow=25, cmap = "tab20",
      4                  height=6, width=10, ax=None)

File ~\.conda\envs\Riskfolio\Lib\site-packages\riskfolio\src\PlotFunctions.py:643, in plot_pie(w, title, others, nrow, cmap, n_colors, height, width, ax)
    641     item.columns = ["labels", "abs_values", "values"]
    642     sizes2 = sizes2[sizes2.index <= l]
--> 643     sizes2 = sizes2.append(item)
    645 abs_sizes = sizes2["abs_values"].tolist()
    646 sizes = sizes2["values"].tolist()

File ~\.conda\envs\Riskfolio\Lib\site-packages\pandas\core\generic.py:5989, in NDFrame.__getattr__(self, name)
   5982 if (
   5983     name not in self._internal_names_set
   5984     and name not in self._metadata
   5985     and name not in self._accessors
   5986     and self._info_axis._can_hold_identifiers_and_holds_name(name)
   5987 ):
   5988     return self[name]
-> 5989 return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'append'

**Comment by dcajasn** [comment] 2023-04-13 21:26
Which version of Pandas are you using?

**Comment by plajos1** [comment] 2023-04-14 15:11
1.5.3

**Comment by dcajasn** [comment] 2023-04-14 17:08
Use panda 1.3, until I update Riskfolio for a new pandas version.

**Comment by plajos1** [comment] 2023-04-17 13:36
With that it works fine...

**Comment by dcajasn** [comment] 2023-05-03 18:00
Hi @plajos1,

It was fixed on version 4.2.0.

Best,
Dany

**Closed by dcajasn** 2023-05-03 18:00 UTC
